DROP TABLE service_user_sns;
DROP TABLE service_user;
DROP TABLE service_user_role;

-- 회원 권한 테이블
CREATE TABLE service_user_role (
    USER_ROLE_ID BIGSERIAL PRIMARY KEY,
    ROLE_NAME VARCHAR(40) UNIQUE NOT NULL,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
COMMENT ON COLUMN service_user_role.USER_ROLE_ID IS '회원 권한 시퀀스';
COMMENT ON COLUMN service_user_role.ROLE_NAME IS '권한명';
COMMENT ON COLUMN service_user_role.CREATED_AT IS '생성일시';
COMMENT ON COLUMN service_user_role.UPDATED_AT IS '최종 수정일시';

-- 회원 테이블
CREATE TABLE service_user (
    USER_ID BIGSERIAL PRIMARY KEY,
    USER_ROLE_ID BIGSERIAL NOT NULL,
    EMAIL VARCHAR(255) UNIQUE NOT NULL,
    PASSWORD VARCHAR(255) NOT NULL,
    ACTIVATION_YN BOOLEAN NOT NULL DEFAULT TRUE,
    DELETE_YN BOOLEAN NOT NULL DEFAULT FALSE,
    USE_PERIOD_START_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    USE_PERIOD_END_AT TIMESTAMP,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY(USER_ROLE_ID) REFERENCES service_user_role(USER_ROLE_ID)
);
COMMENT ON COLUMN service_user.USER_ID IS '회원 시퀀스';
COMMENT ON COLUMN service_user.USER_ROLE_ID IS '회원 권한 시퀀스';
COMMENT ON COLUMN service_user.EMAIL IS '계정 이메일';
COMMENT ON COLUMN service_user.PASSWORD IS '계정 비밀번호';
COMMENT ON COLUMN service_user.ACTIVATION_YN IS '활동여부';
COMMENT ON COLUMN service_user.DELETE_YN IS '삭제여부';
COMMENT ON COLUMN service_user.USE_PERIOD_START_AT IS '가입일시';
COMMENT ON COLUMN service_user.USE_PERIOD_END_AT IS '탈퇴일시';
COMMENT ON COLUMN service_user.CREATED_AT IS '생성일시';
COMMENT ON COLUMN service_user.UPDATED_AT IS '최종 수정일시';

-- SNS 회원 테이블
CREATE TABLE service_user_sns (
    SNS_USER_ID BIGSERIAL PRIMARY KEY,
    USER_ID BIGSERIAL NOT NULL,
    ACCESS_TOKEN VARCHAR(255) NOT NULL,
    PLATFORM VARCHAR(40) NOT NULL,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY(USER_ID) REFERENCES service_user(USER_ID)
);
COMMENT ON COLUMN service_user_sns.SNS_USER_ID IS 'SNS 회원 시퀀스';
COMMENT ON COLUMN service_user_sns.USER_ID IS '회원 시퀀스';
COMMENT ON COLUMN service_user_sns.ACCESS_TOKEN IS '엑세스 토큰';
COMMENT ON COLUMN service_user_sns.PLATFORM IS 'SNS 플랫폼';
COMMENT ON COLUMN service_user_sns.CREATED_AT IS '생성일시';
COMMENT ON COLUMN service_user_sns.UPDATED_AT IS '최종 수정일시';